# Generated by Django 5.0 on 2024-02-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_post_likes_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
